# Generated by Django 4.2.5 on 2024-03-04 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=2000)),
                ('Country', models.CharField(max_length=2000)),
                ('Logo', models.CharField(max_length=2000)),
                ('City', models.CharField(max_length=2000)),
                ('StadiumName', models.CharField(max_length=2000)),
                ('StadiumImg', models.CharField(max_length=2000)),
                ('score', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='leaderboard',
            old_name='name',
            new_name='Name',
        ),
        migrations.RenameField(
            model_name='leaderboard',
            old_name='score',
            new_name='Score',
        ),
    ]
