# Generated by Django 4.2.5 on 2024-03-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_remove_teams_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='teams',
            name='StadiumCapacity',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
    ]
